name: CI

on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.10.3
          run_install: true

      - name: check changeset
        run: pnpm changeset -- status
